Added getters for multiple variables at the same time
sparkfun/SparkFun_BNO080_Arduino_Library pull request #56
Opened 2020-09-17 12:32 UTC by guihomework

As discussed here #55 , this PR adds getters for multiple variables at the same time, also avoiding extra data copy.

Example was tested on SPI1 on a teensy 4.0 but can be modified to test on a standard i2c bus that I cannot test right now immediately

2020-09-18 07:57 UTC, PaulZC requested changes
This is a nice PR - thank you. But it needs a few changes...
Please see the review comments.
Best wishes,
Paul

2020-09-18 07:57 UTC, PaulZC commented on examples/Example16-AccessMultiple/Example16-AccessMultiple.ino
> +/*
Hi @guihomework ,
Thank you for submitting this PR.
Some changes are required...
We already have an Example16. Please change the title of this file to Example18-AccessMultiple.ino.
We have separate examples for I2C and SPI. Please change this example so it uses I2C. You can include a separate SPI example in the SPI\examples folder.
Please comment out the Teensy-specific setMOSI commands etc.. Please see the other SPI examples and use the same format - using generic SPI. It is OK to leave the Teensy code in - so long as it is commented.
I think you missed an '&'? (See comment below.
Thank you!
Paul

2020-09-18 07:57 UTC, PaulZC commented on examples/Example16-AccessMultiple/Example16-AccessMultiple.ino
> +  SPI1.setMOSI(imuMOSIPin);
Please comment these lines.

2020-09-18 07:57 UTC, PaulZC commented on examples/Example16-AccessMultiple/Example16-AccessMultiple.ino
> +  SPI1.setMOSI(imuMOSIPin);
Also, please use the new SPI terminology:
We don't use the terms Master and Slave any more. We now use Controller and Peripheral. We would like all new code to use the new terms: CIPO and COPI.
https://www.oshwa.org/2020/06/29/a-resolution-to-redefine-spi-pin-names/

2020-09-18 07:57 UTC, PaulZC commented on examples/Example16-AccessMultiple/Example16-AccessMultiple.ino
> +  imu_initialized = myIMU.beginSPI(imuCSPin, imuWAKPin, imuINTPin, imuRSTPin, 3000000, SPI1); //changed from slaveCPin
Please comment this line and add a line without the ```3000000, SPI1``` to make the example generic to SPI.

2020-09-18 07:57 UTC, PaulZC commented on examples/Example16-AccessMultiple/Example16-AccessMultiple.ino
> +  SPI1.setMOSI(imuMOSIPin);
(You cannot do anything about ```setMOSI``` but you can change ```imuMOSIPin``` to ```imuCOPIPin``` etc.)

2020-09-18 07:57 UTC, PaulZC commented on examples/Example16-AccessMultiple/Example16-AccessMultiple.ino
> +  }
It might be best to add a warning here that the IMU did not initialize (instead of doing it in the main loop?)?

2020-09-18 07:57 UTC, PaulZC commented on src/SparkFun_BNO080_Arduino_Library.cpp
> +void BNO080::getQuat(float &i, float &j, float &k, float &real, float radaccuracy, uint8_t &accuracy)
I think you forgot the & and capital A for &rad**A**ccuracy?

2020-09-18 07:57 UTC, PaulZC commented on src/SparkFun_BNO080_Arduino_Library.h
> +	void getQuat(float &i, float &j, float &k, float &real, float radAccuracy, uint8_t &accuracy);
Same comment: I think you forgot the & for radAccuracy?

2020-09-18 07:57 UTC, PaulZC commented on examples/Example16-AccessMultiple/Example16-AccessMultiple.ino
> +/*
This is a nice PR. Great work!
Please make the suggested changes and I will be happy to merge it.
Best wishes,
Paul

2020-09-18 15:41 UTC, guihomework commented
Hi @PaulZC  thanks for reviewing and sorry for the bad PR, not looking carefully about the existing examples, not noticing there were SPI separate examples and not being aware that a renaming campaign is underway in the world of programming/electronics.

I hope I tackled all your remarks, but cannot test i2c or spi code in generic fashion. I re-tested with my teensy4.0 while uncommenting the required lines.

2020-09-18 17:16 UTC, PaulZC commented
Hi @guihomework ,
Don't worry! It is a very nice PR. It just needs a little "fine tuning".
I will merge and test this as soon as I can - but it might not be until Monday.
Best wishes - and thank you again,
Paul

2020-09-23 07:02 UTC, PaulZC commented
Thanks again for this PR - and for making the changes!
I am merging this into the release-candidate branch so I can test it.
I will merge into the master branch when we release v1.1.9.

2020-09-23 07:03 UTC, merged